"""
erd.py — docs/ERD.mmd

A Mermaid entity-relationship diagram of the indexed objects. Emitted as a raw
`.mmd` file (not fenced Markdown) so it can be piped straight into the Mermaid
CLI, embedded in a wiki, or rendered by an IDE preview.

Relationships come from two sources: `referenceTo` on indexed lookup/master-detail
fields, and the `relationships` list the object spec carries. Objects referenced
only as a lookup target are drawn as external entities so the graph stays
connected without inventing fields for them.
"""

from __future__ import annotations

from rtk_sf.docgen.extract import ProjectModel
from rtk_sf.docgen.render import now_stamp, sanitize_id

OUTPUT = "ERD.mmd"
TITLE = "Entity Relationship Diagram"

# Attributes per entity — a 300-field object would make the diagram unusable.
MAX_ATTRIBUTES = 12


def generate(model: ProjectModel, **_: object) -> str:
    lines = [
        "%% Generated by rtk-sf `export_system_documentation`.",
        "%% Regenerate rather than hand-editing: local edits are overwritten.",
        f"%% Project: {model.project_root.name} — generated {now_stamp()}",
        "erDiagram",
    ]

    if not model.objects:
        lines.append("    NO_OBJECTS_INDEXED {")
        lines.append("        string note \"Run rtk-sf index first\"")
        lines.append("    }")
        return "\n".join(lines) + "\n"

    known = {obj.name for obj in model.objects.values()}
    external: set[str] = set()
    relationships: list[str] = []

    for obj in model.objects.values():
        entity = sanitize_id(obj.name)
        lines.append(f"    {entity} {{")
        for field in _attributes(obj):
            kind = sanitize_id(field.field_type or "field").lower() or "field"
            flag = " PK" if field.name.lower() == "id" else (" FK" if field.reference_to else "")
            comment = _comment(field)
            lines.append(f"        {kind} {sanitize_id(field.name)}{flag}{comment}")
        if not _attributes(obj):
            lines.append('        string Id PK "no fields indexed for this object"')
        lines.append("    }")

        for field in obj.fields:
            if not field.reference_to:
                continue
            target = field.reference_to
            if target not in known:
                external.add(target)
            cardinality = "||--o{" if _is_master_detail(field) else "}o--||"
            relationships.append(
                f"    {sanitize_id(target)} {cardinality} {entity} : \"{field.name}\""
            )

        for target in obj.relationships:
            if target in known or target in external:
                continue
            external.add(target)
            relationships.append(
                f"    {sanitize_id(target)} ||--o{{ {entity} : \"related\""
            )

    for name in sorted(external):
        lines.append(f"    {sanitize_id(name)} {{")
        lines.append("        string Id PK")
        lines.append("        string note \"referenced only — not indexed here\"")
        lines.append("    }")

    lines.extend(dict.fromkeys(relationships))
    return "\n".join(lines) + "\n"


def _attributes(obj) -> list:
    """Most informative fields first: identifying, required, then the rest."""
    ranked = sorted(
        obj.fields,
        key=lambda f: (
            not f.reference_to,
            not f.required,
            not bool(f.formula),
            f.name.lower(),
        ),
    )
    return ranked[:MAX_ATTRIBUTES]


def _comment(field) -> str:
    notes = []
    if field.required:
        notes.append("required")
    if field.formula:
        notes.append("formula")
    if field.picklist_values:
        notes.append("picklist: " + "/".join(field.picklist_values[:4]))
    if not notes:
        return ""
    text = "; ".join(notes).replace('"', "'")
    return f' "{text}"'


def _is_master_detail(field) -> bool:
    return (field.field_type or "").lower() == "masterdetail"
