"""
render.py — shared Markdown/Mermaid helpers for the doc generators.

Kept deliberately dependency-free: rtk-sf ships with watchdog and pyyaml only,
so documents are assembled with plain string building rather than a template
engine. Every generator writes through these helpers so headings, tables and
provenance banners stay consistent across the document set.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from datetime import datetime, timezone
from typing import Any

# Printed wherever a fact genuinely cannot be derived from the index or source.
# Generators must use this instead of inventing plausible content. It is NOT the
# same as an empty cell: absence that we positively established renders as EMPTY.
UNKNOWN = "_undetermined_"

# "Nothing here, and we know it" — e.g. a method that performs no DML.
EMPTY = "—"

_BANNER = (
    "<!-- Generated by rtk-sf `export_system_documentation`. "
    "Regenerate rather than hand-editing: local edits are overwritten. -->"
)


def now_stamp() -> str:
    """Human-readable UTC timestamp for document headers."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def doc_header(title: str, subtitle: str, project: str, counts: str = "") -> str:
    """Standard document preamble: banner, H1, and a provenance line."""
    lines = [
        _BANNER,
        "",
        f"# {title}",
        "",
        f"_{subtitle}_",
        "",
        f"**Project:** `{project}`  ",
        f"**Generated:** {now_stamp()}  ",
    ]
    if counts:
        lines.append(f"**Scope:** {counts}  ")
    lines.append("")
    return "\n".join(lines)


def section(text: str, level: int = 2) -> str:
    return f"\n{'#' * level} {text}\n"


def cell(value: Any) -> str:
    """Render one table cell: escape pipes and flatten newlines."""
    if value is None:
        return EMPTY
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (list, tuple, set)):
        return joined(list(value))
    text = str(value).strip()
    if not text:
        return EMPTY
    return text.replace("|", "\\|").replace("\n", " ")


def table(headers: Sequence[str], rows: Iterable[Sequence[Any]], empty: str = "") -> str:
    """A GitHub-flavored Markdown table, or `empty` when there are no rows."""
    body = [[cell(value) for value in row] for row in rows]
    if not body:
        return f"{empty}\n" if empty else ""
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    out.extend("| " + " | ".join(row) + " |" for row in body)
    return "\n".join(out) + "\n"


def joined(items: Iterable[Any], sep: str = ", ", empty: str = "") -> str:
    values = [str(item).strip() for item in items if str(item).strip()]
    return sep.join(values) if values else empty


def code(items: Iterable[Any], sep: str = ", ", empty: str = "") -> str:
    """Join items as inline code spans."""
    values = [f"`{item}`" for item in items if str(item).strip()]
    return sep.join(values) if values else empty


def bullets(items: Iterable[Any], indent: int = 0, empty: str = "") -> str:
    pad = " " * indent
    lines = [f"{pad}- {item}" for item in items if str(item).strip()]
    if not lines:
        return f"{pad}- {empty}\n" if empty else ""
    return "\n".join(lines) + "\n"


def numbered(items: Iterable[Any], empty: str = "") -> str:
    lines = [f"{i}. {item}" for i, item in enumerate(items, 1) if str(item).strip()]
    if not lines:
        return f"1. {empty}\n" if empty else ""
    return "\n".join(lines) + "\n"


def mermaid(body: str) -> str:
    """Wrap Mermaid source in a fenced block GitHub renders natively."""
    return "```mermaid\n" + body.rstrip() + "\n```\n"


def code_block(body: str, lang: str = "") -> str:
    return f"```{lang}\n" + body.rstrip() + "\n```\n"


def truncate(text: str, limit: int = 160) -> str:
    text = " ".join(str(text).split())
    return text if len(text) <= limit else text[: limit - 1] + "…"


def sanitize_id(name: str) -> str:
    """Mermaid-safe participant/entity identifier."""
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in str(name))
    return cleaned.strip("_") or "node"


def empty_notice(what: str) -> str:
    """Body used when the index holds nothing for a document."""
    return (
        f"No {what} found in the rtk-sf index.\n\n"
        "Run `rtk-sf index` (or `python3 -m rtk_sf index`) against the project "
        "first, then regenerate this document.\n"
    )
